apiVersion: v1
kind: Service
metadata:
  name: deliverycostcalculator
labels:
  app: deliverycostcalculator
spec:
  ports:
    port: 8080
    targetPort: 8080
    selector:
      app: deliverycostcalculator
    type: NodePort